import re

from app.schemas.demand_schema import ParsedReplyResponse


class ReplyParseService:
    LINE_PATTERN = re.compile(
        r"^\s*(?P<sku_code>[A-Za-z0-9_-]+)\s*(?:[-:]\s*|\s+)(?P<monthly_quantity>\d+)\s*$"
    )

    def parse_reply(
        self,
        distributor_code: str,
        raw_reply_text: str | None = None,
        confirmed_by: str | None = None,
        notes: str | None = None,
    ) -> ParsedReplyResponse:
        if raw_reply_text and raw_reply_text.strip():
            parsed_lines = self._parse_raw_reply_text(raw_reply_text)
            normalized_notes = notes or "Parsed from raw distributor reply text."
        else:
            parsed_lines = self._build_placeholder_lines()
            normalized_notes = notes or "Placeholder parsed reply generated by ReplyParseService."

        return ParsedReplyResponse(
            distributor_code=distributor_code,
            confirmed_by=confirmed_by,
            notes=normalized_notes,
            parsed_lines=parsed_lines,
        )

    def _parse_raw_reply_text(self, raw_reply_text: str) -> list[dict]:
        parsed_lines: list[dict] = []

        for raw_line in raw_reply_text.splitlines():
            stripped_line = raw_line.strip()
            if not stripped_line:
                continue

            match = self.LINE_PATTERN.match(stripped_line)
            if not match:
                continue

            parsed_lines.append(
                self._normalize_line(
                    {
                        "sku_code": match.group("sku_code").upper(),
                        "sku_name": None,
                        "monthly_quantity": int(match.group("monthly_quantity")),
                        "raw_text": stripped_line,
                    }
                )
            )

        return parsed_lines

    def _build_placeholder_lines(self) -> list[dict]:
        return [
            self._normalize_line(
                {
                    "sku_code": "SKU001",
                    "sku_name": "Mock Product 1",
                    "monthly_quantity": 120,
                    "raw_text": "SKU001 - 120",
                }
            ),
            self._normalize_line(
                {
                    "sku_code": "SKU002",
                    "sku_name": "Mock Product 2",
                    "monthly_quantity": 80,
                    "raw_text": "SKU002: 80",
                }
            ),
        ]

    @staticmethod
    def _normalize_line(line: dict) -> dict:
        return {
            "sku_code": line.get("sku_code", ""),
            "sku_name": line.get("sku_name"),
            "monthly_quantity": line.get("monthly_quantity"),
            "raw_text": line.get("raw_text"),
        }
