from app.schemas.demand_schema import ParsedReplyResponse


class ReplyParseService:
    def parse_reply(self, distributor_code: str) -> ParsedReplyResponse:
        return ParsedReplyResponse(
            distributor_code=distributor_code,
            confirmed_by="Mock Distributor Contact",
            notes="Placeholder parsed reply generated by ReplyParseService.",
            parsed_lines=[
                {
                    "sku_code": "SKU001",
                    "sku_name": "Mock Product 1",
                    "monthly_quantity": 120,
                    "raw_text": "SKU001 - Mock Product 1 - 120",
                },
                {
                    "sku_code": "SKU002",
                    "sku_name": "Mock Product 2",
                    "monthly_quantity": 80,
                    "raw_text": "SKU002 - Mock Product 2 - 80",
                },
            ],
        )
